---
label: project
hide_body: true
fields:
- type: text
  name: title
  label: title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: category
  type: select
  default: ''
  config:
    required: false
    options:
    - Stavba
    - Návrh
    - Film
    source:
      type: simple
      section: 
      file: 
      path: 
  label: category
  description: typo of project
- name: year
  type: text
  config:
    required: false
  label: year
- type: image_gallery
  name: images
  label: images
- type: text
  name: slug
  label: slug
  hidden: true
- type: text
  name: layout
  label: layout
  default: project
  config:
    required: true
  hidden: true
pages:
- _projects/glori.md
- _projects/digita-naive.md
- _projects/futura.md
- _projects/lejdy-karneval.md
