---
label: project
hide_body: false
fields:
- name: embed
  type: text
  config:
    required: false
  label: embed
- name: weight
  type: number
  label: weight
  description: ''
  default: '9999'
  required: true
  config:
    min: 
    max: 
    step: 
- type: text
  name: title
  label: title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: year
  type: text
  config:
    required: false
  label: year
- type: image_gallery
  name: images
  label: images
- name: gallery
  type: image_gallery
  config: {}
  label: gallery
- name: category
  type: select
  default: ''
  config:
    required: false
    options:
    - Stavba
    - Návrh
    - Film
    source:
      type: simple
      section: 
      file: 
      path: 
  label: category
  description: typo of project
- type: text
  name: slug
  label: slug
  hidden: true
- type: text
  name: layout
  label: layout
  default: project
  config:
    required: true
  hidden: true
pages:
- _projects/all-that-you-change-changes-you.md
- _projects/both-bodies-clove.md
- _projects/coma.md
- _projects/digita-naive.md
- _projects/futura.md
- _projects/glori.md
- _projects/lejdy-karneval.md
- _projects/plankton.md
- _projects/rest-bags.md
- _projects/s-a-d.md
- _projects/work-hard-in-silence-1.md
- _projects/work-hard-in-silence.md
